import { ReactNode } from "react"

const Head = ({
  children
}: {children: ReactNode}) => (
  <>
    {children}
    <meta content='width=device-width, initial-scale=1' name='viewport' />
    <meta name='description' content='Generated by create next app' />
    <link rel='icon' href='/logo.svg' />
  </>
)

export default Head
